### PR TITLE
Fix links in README to testing and docs contributor documentation

### PR DESCRIPTION
**Pull request by marios**

### CODE REVIEW

**Comment by marios** [comment]
mainly I wanted to test the skeleton job I am working on (https://review.rdoproject.org/zuul/builds?job_name=data-plane-adoption-github-rdo-centos-8-crc-centos-9-standalone) and also noticed this readme nit

**Comment by marios** [comment]
check-github

**Comment by jistr** [comment]
Do you want to keep this open for now, to test the job?

**Comment by marios** [comment]
yes please lets keep it for a little longer so i can test maybe we will merge it tomorrow and i can just post a new DNM pull request or something if needed

**Comment by raukadah** [comment]
check-rdo

**Comment by marios** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by marios** [comment]
@jistr thanks you can go ahead and merge this when ready thank you... we got the job running at https://github.com/openstack-k8s-operators/data-plane-adoption/pull/19

**Comment by jistr** [comment]
Great, thanks!

**Review by jistr — APPROVED** [review]

**Pull request merged**
