### PR TITLE
Remove `edpm_encoded_privatekey` workaround

### PR DESCRIPTION
**Pull request by fao89**
As agreed, removing the workaround after merging https://review.rdoproject.org/r/c/rdo-jobs/+/49298

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by marios — APPROVED** [review]

**Comment by marios** [comment]
lgtm and green run here https://review.rdoproject.org/zuul/buildset/74c53e39eabf4901b47669e896edb020

going to merge @fao89 ... other cores are out this week and this is a simple fix that follows on from yesterday's merge

**Pull request merged**
