### PR TITLE
Use nodeset_networks ansible var

### PR DESCRIPTION
**Pull request by rabi**
There is no concept of role anymore.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
TASK [osp.edpm.edpm_bootstrap : Ensure packages are actually well installed] ***
Friday 29 March 2024  03:47:17 +0000 (0:00:01.686)       0:00:16.510 ********** 
[0;31mfatal: [standalone]: FAILED! => {"changed": false, "cmd": ["rpm", "-V", "driverctl", "lvm2", "crudini", "jq", "nftables", "NetworkManager", "openstack-selinux", "python3-libselinux", "python3-pyyaml", "rsync", "tmpwatch", "sysstat", "iproute-tc", "ksmtuned", "systemd-container", "crypto-policies-scripts", "grubby"], "delta": "0:00:00.874334", "end": "2024-03-29 03:47:18.450477", "failed_when_result": true, "msg": "non-zero return code", "rc": 2, "start": "2024-03-29 03:47:17.576143", "stderr": "error: %verify(openstack-selinux-0.8.39-0.20240219135314.f618d90.el9.noarch) scriptlet failed, exit status 1", "stderr_lines": ["error: %verify(openstack-selinux-0.8.39-0.20240219135314.f618d90.el9.noarch) scriptlet failed, exit status 1"], "stdout": "S.5....T.  c /etc/NetworkManager/NetworkManager.conf\nMissing os-ceilometer!\nFound 1 missing module(s).", "stdout_lines": ["S.5....T.  c /etc/NetworkManager/NetworkManager.conf", "Missing os-ceilometer!", "Found 1 missing module(s)."]}[0m

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
can someone merge this one?

**Review by jistr — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
