### PR TITLE
Switch ansible vars

### PR DESCRIPTION
**Pull request by rabi**
Align with changes in dataplane-operator

ref: https://github.com/openstack-k8s-operators/dataplane-operator/pull/614

### CODE REVIEW

**Comment by rabi** [comment]
recheck RETRY_LIMIT

**Comment by rabi** [comment]
recheck

**Comment by son-vyas** [comment]
recheck

**Comment by rabi** [comment]
> recheck

This job won't work until https://github.com/openstack-k8s-operators/openstack-operator/pull/639 is merged or added as `Depends-On` here. We can either force merge this or wait for https://github.com/openstack-k8s-operators/openstack-operator/pull/639 to be merged and  then `recheck`.

**Comment by jistr** [comment]
If we need this to validate that https://github.com/openstack-k8s-operators/openstack-operator/pull/639 is good to merge then we can add the depends-on here, and if it's green here, then we force-merge the openstack-operator PR, and subsequently merge this one too?

**Comment by rabi** [comment]
> then we can add the depends-on here, and if it's green here

FWIW, dataplane adoption job is green[1] in https://github.com/openstack-k8s-operators/openstack-operator/pull/639 with this as Depends-On. Just that it's stuck with cycle of random unrelated failures in one job at a time. We can safely force merge this if we want.

[1] https://review.rdoproject.org/zuul/build/018490e96bde4250a6463909ecf94b72

**Comment by jistr** [comment]
> We can safely force merge this if we want.

If this is true:

> This job won't work until https://github.com/openstack-k8s-operators/openstack-operator/pull/639 is merged or added as Depends-On here.

Then we can only safely force-merge this PR after https://github.com/openstack-k8s-operators/openstack-operator/pull/639 is merged IIUC.

**Comment by rabi** [comment]
> Then we can only safely force-merge this PR after [openstack-k8s-operators/openstack-operator#639](https://github.com/openstack-k8s-operators/openstack-operator/pull/639) is merged IIUC.

Well, we can also use the normal workflow i.e recheck/approve this PR once https://github.com/openstack-k8s-operators/openstack-operator/pull/639 has been merged. I mentioned about force merging this to reverse the order and expedite. Anyway, openstack-operator PR should merge soon.

**Review by fao89 — APPROVED** [review]
thank you!

**Comment by viroel** [comment]
recheck

**Comment by rabi** [comment]
Don't we use auto-merging with tide in this repo?

**Comment by lewisdenny** [comment]
> Don't we use auto-merging with tide in this repo?

No, Tide isn't set up in this repo [1], I can set it up if requested though

[1] https://github.com/lewisdenny/release/tree/master/core-services/prow/02_config/openstack-k8s-operators

**Review by jistr — APPROVED** [review]

**Comment by jistr** [comment]
Thanks!

**Pull request merged**
