### PR TITLE
Switch MariaDB to Galera in tests/docs

### PR DESCRIPTION
**Pull request by bogdando**
Use galera with 1 replica for docs, tests, CI
Also stop HAProxy and Galera pcmk resources.

Related JRA OSPRH-2039 https://issues.redhat.com/browse/OSPRH-2039

### CODE REVIEW

**Comment by bogdando** [comment]
@jistr I needed this case when testing adoption with a custom CR from install_yamls (with galera DB and isolnet)

**Comment by bogdando** [comment]
updated with new edpm changes rebased

**Comment by bogdando** [comment]
I'm not sure why it failed (before the openstack services stopped)
```
"+ podman run -i --rm --userns=keep-id -u 1000 -v /home/zuul/src/github.com/openstack-k8s-operators/data-plane-adoption/tests/playbooks:/home/zuul/src/github.com/openstack-k8s-operators/data-plane-adoption/tests/playbooks:z,rw -w /home/zuul/src/github.com/openstack-k8s-operators/data-plane-adoption/tests/playbooks quay.io/podified-antelope-centos9/openstack-mariadb:current-podified mysql -h 192.168.122.100 -uroot -p<snip> -e 'SHOW databases;'",
"Trying to pull quay.io/podified-antelope-centos9/openstack-mariadb:current-podified...",
...
"ERROR 2002 (HY000): Can't connect to MySQL server on '192.168.122.100' (115)"], }
```

**Review by jistr — APPROVED** [review]
Thank you :+1:

**Comment by bogdando** [comment]
recheck RETRY_LIMIT

**Review by marios — CHANGES_REQUESTED** [review]
lgtm but I think it needs a rebase ('out of date with main branch') 

also i just poked at logs a bit... are those errors ok - they seem to happen ~10 mins after the previous message and continue to the end of logfile

https://logserver.rdoproject.org/56/156/8f370f117149f8344af791255d91439539365c3b/github-check/data-plane-adoption-OSP-17-to-extracted-crc/b3f976d/controller/pod/openstack-cell1-galera-0-logs.txt
```
2023-12-06 18:02:06 163 [Warning] Aborted connection 163 to db: 'nova_cell1' user: 'nova_cell1' host: '10.217.1.19' (Got an error reading communication packets)
2023-12-06 18:19:51 171 [Warning] Aborted connection 171 to db: 'nova_cell1' user: 'nova_cell1' host: '10.217.1.32' (Got an error reading communication packets)
```

and https://logserver.rdoproject.org/56/156/8f370f117149f8344af791255d91439539365c3b/github-check/data-plane-adoption-OSP-17-to-extracted-crc/b3f976d/controller/pod/openstack-galera-0-logs.txt

```
2023-12-06 17:58:00 128 [Warning] Aborted connection 128 to db: 'keystone' user: 'keystone' host: '10.217.0.248' (Got an error reading communication packets)
2023-12-06 17:58:10 131 [Warning] Aborted connection 131 to db: 'keystone' user: 'keystone' host: '10.217.0.249' (Got an error reading communication packets)

```

**Comment by bogdando** [comment]
> Aborted connection 163 to db

IIRC those are notorious red herriing messages been here since openstack HA beginning. @dciabrin may know more about that

**Comment by marios** [comment]
recheck 



seems like a one off thing lets see

https://logserver.rdoproject.org/56/156/a8778812f5b0479bc18e437e63a0943990dd77e9/github-check/data-plane-adoption-OSP-17-to-extracted-crc/7b79e7a/job-output.txt

```
2023-12-08 09:07:02.438491 | controller | fatal: [localhost]: FAILED! => {"attempts": 1, "changed": true, "checksum": "0c2c92ac0bd90db40183dc6d818ec8e68c46c1fb", "cmd": "/usr/bin/gmake netconfig_deploy", "dest": "/home/zuul/ci-framework-data/artifacts/ci_make_004_run_netconfig_deploy.sh", "gid": 1000, "group": "zuul", "md5sum": "5b447ebca2ab0c3fc09d71f9ada0748b", "mode": "0755", "msg": "+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests ']'\n+ '[' -z openstack ']'\n+ OUT_DIR=/home/zuul/ci-framework-data/artifacts/manifests/openstack\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openstack ']'\n+ cat\nerror: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~)\ngmake: *** [Makefile:535: namespace] Error 1", "owner": "zuul", "rc": 2, "secontext": "
```

**Review by marios — APPROVED** [review]

**Comment by marios** [comment]
lets please hold for current run - expected to be green (it was on friday) and we can merge it today

**Comment by bogdando** [comment]
CI failure looks unrelated, but likely will hit it again?
```
TASK [dataplane_adoption : force latest ansible-runner image] ******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "set -euxo pipefail


oc login -u kubeadmin -p 123456789

# openstack-operator catalog pins the sha256, which might differ from latest with time
oc patch csv -n openstack-operators openstack-ansibleee-operator.v0.0.1  --type='json' -p='[{
  \"op\":\"replace\", \"path\":\"/spec/install/spec/deployments/0/spec/template/spec/containers/1/env/0\",
  \"value\": {\"name\": \"RELATED_IMAGE_ANSIBLEEE_IMAGE_URL_DEFAULT\", \"value\": \"quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest\"}}]'
",
"delta": "0:00:05.176404",
"end": "2023-12-11 04:29:26.614523",
"msg": "non-zero return code",
"rc": 1, "start": "2023-12-11 04:29:21.438119",
"stderr": "+ oc login -u kubeadmin -p 123456789
error: server_error The authorization server encountered an unexpected condition that prevented it from fulfilling the request.",
"stderr_lines": ["+ oc login -u kubeadmin -p 123456789",
"error: server_error The authorization server encountered an unexpected condition that prevented it from fulfilling the request."], "stdout": "WARNING: Using insecure TLS client config. Setting this option is not supported!",
"stdout_lines": ["WARNING: Using insecure TLS client config. Setting this option is not supported!"]}
```

**Comment by bogdando** [comment]
recheck

**Comment by marios** [comment]
sorry @bogdando but it needs rebase again. Once you update i can merge w/out waiting for the run it was green again in the recent run here https://review.rdoproject.org/zuul/buildset/3807378b92ec46868a666ebf4aea270c

**Comment by bogdando** [comment]
@jistr please merge this one

**Pull request merged**
