### PR TITLE
[18.0-fr1] Catch up to changes that landed on main and are relevant for 18.0-fr1

### PR DESCRIPTION
**Pull request by jistr**

### CODE REVIEW

**Comment by jistr** [comment]
As long as there is common history, this is just fast-forwarding the `18.0-fr1` branch along the `main` branch. At some point i had to leave out a commit and from there the cherry picks are starting. The commit titled "Add missing neutron agents to openstack_version" is the first cherry-pick.

**Comment by jistr** [comment]
Includes backports of #649, #658, #662, #664, #672, #677, #678, #679, #680, #682, #684, #685, #693, #694, #695, #697.

**Review by klgill — APPROVED** [review]
I checked all of my commits. LGTM.

**Comment by ciecierski** [comment]
recheck

**Pull request merged**
