### PR TITLE
Restores the name of the data-plane-adoption no ceph job

### PR DESCRIPTION
**Pull request by frenzyfriday**
Depends-On: https://review.rdoproject.org/r/c/rdo-jobs/+/53044

### CODE REVIEW

**Comment by frenzyfriday** [comment]
recheck

**Comment by frenzyfriday** [comment]
recheck

**Comment by frenzyfriday** [comment]
recheck

**Review by cescgina — APPROVED** [review]

**Review by marios — APPROVED** [review]
lgtm thanks

**Pull request merged**
