### PR TITLE
Initial deployment of control plane services

### PR DESCRIPTION
**Pull request by jistr**
When enabling all services, some of the containers were erroring out, so those services are commented out for now. Here's how pod list looked with all services enabled:

```
$ oc get pod
NAME                                                              READY   STATUS             RESTARTS         AGE
a36e1b3d106136052b82eb521749965f8e9b0b0c48ab56ddf9ff68acfaf258d   0/1     Completed          0                6d22h
cinder-966758f6d-mc4zk                                            1/1     Running            0                45m
cinder-backup-0                                                   2/2     Running            0                45m
cinder-operator-controller-manager-5476b67b7f-mzf4g               2/2     Running            0                6d22h
cinder-scheduler-0                                                2/2     Running            0                45m
cinder-volume-volume1-0                                           0/2     CrashLoopBackOff   26 (2m14s ago)   45m
controller-manager-cf8c8bb6c-2txjd                                1/1     Running            0                6d22h
glance-external-api-b95fb68f8-hc4nr                               1/1     Running            0                79m
glance-internal-api-75859f6bc-2h74z                               1/1     Running            0                79m
glance-operator-controller-manager-5978fdfbdc-hfjvv               2/2     Running            0                6d22h
keystone-5b9c75dbf5-mcnp2                                         1/1     Running            0                94m
keystone-operator-controller-manager-669d5b6fbd-fgr5z             2/2     Running            0                6d22h
mariadb-openstack                                                 1/1     Running            0                105m
mariadb-operator-controller-manager-86f5cdbb6d-48npl              2/2     Running            0                6d22h
neutron-7c548b7bcb-hcgqp                                          1/1     Running            0                40m
neutron-operator-controller-manager-786cf54786-kq7vn              2/2     Running            0                6d22h
nova-api-0                                                        2/2     Running            0                41m
nova-cell0-conductor-0                                            0/1     CrashLoopBackOff   12 (4m3s ago)    41m
nova-operator-controller-manager-7b75ddf84d-vktfv                 2/2     Running            0                6d22h
nova-scheduler-0                                                  0/1     CrashLoopBackOff   12 (117s ago)    41m
openstack-operator-controller-manager-9b644ff7c-csvvt             2/2     Running            0                6d22h
openstack-operator-index-f8xws                                    1/1     Running            0                6d22h
ovn-northd-b95f869d7-t8bmm                                        1/1     Running            0                42m
ovn-operator-controller-manager-545456d787-gjzsw                  2/2     Running            0                6d22h
ovs-hwmqh                                                         3/3     Running            0                42m
ovs-operator-controller-manager-5cf97fb7d4-kt76q                  2/2     Running            0                6d22h
ovsdbserver-nb-0                                                  1/1     Running            0                43m
ovsdbserver-sb-0                                                  1/1     Running            0                43m
placement-74c78d99fc-k9gw5                                        1/1     Running            0                54m
placement-operator-controller-manager-7458f5f8d-qhd6g             2/2     Running            0                6d22h
rabbitmq-server-0                                                 1/1     Running            0                105m
```

One issue with current state is that even if old potentially conflicting Keystone endpoints are cleaned up before deploying the additional services, the correct endpoints aren't created:

```
$ openstack endpoint list
+----------------------------------+-----------+--------------+--------------+---------+-----------+---------------------------------------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                                                 |
+----------------------------------+-----------+--------------+--------------+---------+-----------+---------------------------------------------------------------------+
| 33d5eaa703e642ec9f298fdb565403f4 | regionOne | keystone     | identity     | True    | public    | http://keystone-public-openstack.apps-crc.testing                   |
| 61fbdf9c199946b3a762ec3491caf2dc | regionOne | keystone     | identity     | True    | admin     | http://keystone-admin-openstack.apps-crc.testing                    |
| 79c4c0edf3444a05ad9935c5c316c56e | regionOne | cinderv2     | volumev2     | True    | internal  | http://cinder-internal-openstack.apps-crc.testing/v2/%(project_id)s |
| 7dda18ad52ad474db38a9281bba02708 | regionOne | cinderv2     | volumev2     | True    | public    | http://cinder-public-openstack.apps-crc.testing/v2/%(project_id)s   |
| a6398f3ae38b498fa897bf3e2d4945ab | regionOne | cinderv2     | volumev2     | True    | admin     | http://cinder-admin-openstack.apps-crc.testing/v2/%(project_id)s    |
| e506309742e74e17876065440fc6b62b | regionOne | keystone     | identity     | True    | internal  | http://keystone-internal-openstack.apps-crc.testing                 |
+----------------------------------+-----------+--------------+--------------+---------+-----------+---------------------------------------------------------------------+

$ oc get keystoneendpoint
NAME              STATUS    MESSAGE
cinderv2          True      Setup complete
cinderv3          Unknown   Setup started
glance-external   Unknown   Setup started
glance-internal   Unknown   Setup started
neutron           Unknown   Setup started
nova              Unknown   Setup started
placement         Unknown   Setup started
```

### CODE REVIEW

**Comment by gibizer** [comment]
So think I reproduced the missing endpoint issue. I did the DB adoption and then enabled keystone. I checked via keystone API I see the adopted DB.

Then I enabled placement in OpenstackControlPlane.

It seems the KeystoneEndpoint/placement CR is not created.

```console
1.6751015105132043e+09	INFO	controllers.KeystoneService	Reconciling Service
1.6751015105132368e+09	INFO	controllers.KeystoneService	Reconciling Service placement
1.6751015105602179e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.675101510560341e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.675101511518149e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015115182605e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.675101511575689e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.675101511575735e+09	INFO	controllers.KeystoneService	Reconciling User placement
1.6751015133680308e+09	INFO	controllers.KeystoneService	Reconciled User successfully
1.6751015133680727e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.6751015141385505e+09	INFO	controllers.KeystoneService	Reconciling Service
1.6751015141385846e+09	INFO	controllers.KeystoneService	Reconciling Service placement
1.675101514405663e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.6751015144057066e+09	INFO	controllers.KeystoneService	Reconciling User placement
1.6751015152755387e+09	INFO	controllers.KeystoneService	Reconciled User successfully
1.6751015152755876e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.675101521780395e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015217804852e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015226803963e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015226804826e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015325793645e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.675101532579607e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.675101544086615e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015440912197e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015547542746e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015547543645e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015653387282e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015653407485e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015759407701e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751015759408524e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
```
Interestingly KeystoneService/placement seems to be in good shape according to the conditions. BUT the Ready condition is not in True state: This causing that the KeystoneEndpoint/placement reconciliation waits.
```console
[dpadev@osp-dev-01 ~]$ oc get -o yaml  KeystoneService/placement
apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneService
metadata:
  creationTimestamp: "2023-01-30T17:58:29Z"
  finalizers:
  - PlacementAPI
  - KeystoneService
  generation: 1
  name: placement
  namespace: openstack
  ownerReferences:
  - apiVersion: placement.openstack.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PlacementAPI
    name: placement
    uid: 63510464-0209-49ce-a361-743ba6c44515
  resourceVersion: "3805816"
  uid: 8af677e6-d0db-46d7-b556-a60821df9f03
spec:
  enabled: true
  passwordSelector: PlacementPassword
  secret: osp-secret
  serviceDescription: Placement Service
  serviceName: placement
  serviceType: placement
  serviceUser: placement
status:
  conditions:
  - lastTransitionTime: "2023-01-30T17:58:29Z"
    message: Setup started
    reason: Requested
    status: Unknown
    type: Ready
  - lastTransitionTime: "2023-01-30T17:58:30Z"
    message: Admin client ready
    reason: Ready
    status: "True"
    type: AdminServiceClientReady
  - lastTransitionTime: "2023-01-30T17:58:29Z"
    message: KeystoneAPI ready
    reason: Ready
    status: "True"
    type: KeystoneAPIReady
  - lastTransitionTime: "2023-01-30T17:58:31Z"
    message: Keystone Service placement -  ready
    reason: Ready
    status: "True"
    type: KeystoneServiceOSServiceReady
  - lastTransitionTime: "2023-01-30T17:58:33Z"
    message: Keystone Service user placement ready
    reason: Ready
    status: "True"
    type: KeystoneServiceOSUserReady
[dpadev@osp-dev-01 ~]$ 
```

**Comment by gibizer** [comment]
I tried to reproduce the same issue without adopting a DB and I cannot. When placement is enabled it gets both the KeystoneService and KeystoneEndpoint created successfully:
```console
1.6751565996703002e+09	INFO	controllers.KeystoneService	Reconciling Service
1.6751565996703598e+09	INFO	controllers.KeystoneService	Reconciling Service placement
1.6751565997259078e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751565997259731e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751565998209982e+09	INFO	controllers.KeystoneService	Service Created - Servicename placement, ID 1c1c0d1405424b4583af60b30cc59a30
1.6751565998210547e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.6751565998210669e+09	INFO	controllers.KeystoneService	Reconciling User placement
1.6751565998537924e+09	INFO	controllers.KeystoneService	Creating project service
1.6751565999471872e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751565999472773e+09	INFO	controllers.KeystoneEndpoint	KeystoneService placement not ready, waiting to create endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566001758173e+09	INFO	controllers.KeystoneService	User Created - Username placement, ID dda1505c77174c79b1e6b1327e0c752b
1.6751566002634306e+09	INFO	controllers.KeystoneService	Assigning userID dda1505c77174c79b1e6b1327e0c752b to role admin - 67733ca5643b4db7a5aa788ad2fa4c9c
1.6751566003881469e+09	INFO	controllers.KeystoneService	Role Created - Rolename service, ID 6e4904cac7ce4ecbb4cb8169ebdacc7f
1.6751566004467363e+09	INFO	controllers.KeystoneService	Assigning userID dda1505c77174c79b1e6b1327e0c752b to role service - 6e4904cac7ce4ecbb4cb8169ebdacc7f
1.6751566004983182e+09	INFO	controllers.KeystoneService	Reconciled User successfully
1.6751566004983997e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.6751566006966624e+09	INFO	controllers.KeystoneService	Reconciling Service
1.6751566006967134e+09	INFO	controllers.KeystoneService	Reconciling Service placement
1.6751566007311347e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.6751566007311487e+09	INFO	controllers.KeystoneService	Reconciling User placement
1.6751566009980676e+09	INFO	controllers.KeystoneService	Reconciled User successfully
1.6751566009980834e+09	INFO	controllers.KeystoneService	Reconciled Service successfully
1.675156609929236e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566099292688e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566099292717e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 admin 
1.6751566100190647e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566100190787e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 admin 
1.6751566101582882e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566103078153e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 internal 
1.6751566103711357e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566103711495e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 internal 
1.6751566104834378e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566106045914e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 public 
1.6751566106392038e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566106392236e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 public 
1.6751566106698852e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566107091994e+09	INFO	controllers.KeystoneEndpoint	Reconciled Endpoints successfully	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566107092211e+09	INFO	controllers.KeystoneEndpoint	Reconciled Endpoint normal successfully	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566109259682e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoint normal	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566109260762e+09	INFO	controllers.KeystoneEndpoint	Reconciling Endpoints	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566109261508e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 public 
1.6751566109751925e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.675156610975207e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 admin 
1.6751566110046208e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.6751566110046368e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoints for service 1c1c0d1405424b4583af60b30cc59a30 internal 
1.6751566110339665e+09	INFO	controllers.KeystoneEndpoint	Getting Endpoint successfully
1.675156611034027e+09	INFO	controllers.KeystoneEndpoint	Reconciled Endpoints successfully	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
1.6751566110340455e+09	INFO	controllers.KeystoneEndpoint	Reconciled Endpoint normal successfully	{"ObjectType": "*v1beta1.KeystoneEndpoint", "ObjectNamespace": "openstack", "ObjectName": "placement"}
```

So probably something in the adopted DB causing the different behavior in keystone-operator.

**Comment by gibizer** [comment]
I see one diff in the KeystoneService/placement status:
Adoption:
```console
  - lastTransitionTime: "2023-01-31T09:16:39Z"
    message: Keystone Service placement - 1c1c0d1405424b4583af60b30cc59a30 ready
    reason: Ready
    status: "True"
    type: KeystoneServiceOSServiceReady
```
Empty DB:
```console
  - lastTransitionTime: "2023-01-30T17:58:31Z"
    message: Keystone Service placement -  ready
    reason: Ready
    status: "True"
    type: KeystoneServiceOSServiceReady
```

**Comment by gibizer** [comment]
> 
> According to the keystoneservice_controller's code what it does last it the Service user ready condition. https://github.com/openstack-k8s-operators/keystone-operator/blob/efdd85d844e1cd0180cf66768e86e4f9237d00f8/controllers/keystoneservice_controller.go#L332 and that seems to happened. There is no non True condition in the condition list (except Ready) so Ready should be evaluated to True. @stuggi as you are more familiar with the condition logic we have in lib-common. How this can happen?

@stuggi: scratch that. I noticed that the KeystoneService.IsReady is taking into account the KeystoneService.Status.ServiceID field being non-empty as well
https://github.com/openstack-k8s-operators/keystone-operator/blob/bccb61332d31907bfa35d0562e468dad986d2d94/api/v1beta1/keystoneservice_types.go#L89

Based on the above printouts the ServiceID is missing from the KeystoneService if we are adopting a DB and this causes that the KeystoneService is not Ready.

**Comment by gibizer** [comment]
OK I think I see the root cause: https://github.com/openstack-k8s-operators/keystone-operator/blob/bccb61332d31907bfa35d0562e468dad986d2d94/controllers/keystoneservice_controller.go#L360-L362 

Keystone only stores that ServiceID if it creates the Service in openstack, if the service already exists then it does not read it out and stores it. During adoption the placement service already exists in the DB so the ServiceID is not populated back to the podified control plane. I will push a keystone-operator patch to fix this.

**Comment by gibizer** [comment]
> @gibizer Alternatively we could also clean up the service objects in Keystone just as i cleaned up the endpoints. But maybe achieving idempotence/convergence without manual cleanups is better? Not sure if it can have some downsides too...

I would go with automation.
I pushed a PR https://github.com/openstack-k8s-operators/keystone-operator/pull/168

**Comment by jistr** [comment]
@gibizer :+1:  Thanks i'll try and test that too.

**Comment by gibizer** [comment]
So the PR https://github.com/openstack-k8s-operators/keystone-operator/pull/168 in my test resolves the endpoint creation issue. 

I needed to adjust the secret/osp-secret/PlacementPassword according to the placement password from the adopted deployment. So that the placement.conf has the password that adopted keystone database has. After that I could talk to the placement API via the openstackclient successfully.

**Pull request merged**
