### PR TITLE
Add os-diff to the adoption workflow

### PR DESCRIPTION
**Pull request by matbu**

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
please add your doc here: https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/mkdocs.yml#L29

**Comment by matbu** [comment]
Just FYI, we need to wait a little to land this PR because I have pushed breaking changes waiting for being merged at the os-diff side: https://github.com/openstack-k8s-operators/os-diff/pull/25

**Review by jistr — APPROVED** [review]
I didn't get the chance to use it and i've noticed a few typos in the doc but LGTM, i'm in favor of merging and iterating where needed. It would also be nice to exercise this somehow in CI as discussed on this week's call, but that can be another PR.

**Review by fao89 — APPROVED** [review]

**Comment by jistr** [comment]
This does not touch tests, i'll merge.

**Pull request merged**
