### PR TITLE
Removes data-plane-adoption job defs as patch https://review.rdoproject.org/r/c/rdo-jobs/+/53006 moves them to rdo-jobs

### PR DESCRIPTION
**Pull request by frenzyfriday**

### CODE REVIEW

**Comment by frenzyfriday** [comment]
recheck

**Comment by frenzyfriday** [comment]
nova-compute-extraconfig-openstack-openstack-<id> pods did not come up

**Review by cescgina — APPROVED** [review]

**Review by marios — APPROVED** [review]
lgtm waiting for rdo-jobs side to merge and lets land this

**Comment by marios** [comment]
recheck 

job issue should be fixed per slack discussion

**Comment by marios** [comment]
k, looks like no zuul issues with the 'new' job, the jobs are queued https://review.rdoproject.org/zuul/status/change/419,1f8d8c9877836345148891df6c3222fcd30b280d

**Comment by frenzyfriday** [comment]
recheck

**Pull request merged**
