### PR TITLE
Align glance with the new storage interface

### PR DESCRIPTION
**Pull request by fmount**
Jira: https://issues.redhat.com/browse/OSPRH-6719
Jira: https://issues.redhat.com/browse/OSPRH-7862

### CODE REVIEW

**Comment by fmount** [comment]
@jistr we can link the additional Jira that might require further changes.

**Review by konan-abhi — APPROVED** [review]
Looks good!!

**Comment by fmount** [comment]
> @jistr we can link the additional Jira that might require further changes.

Nevermind, found it and fixed the metalLB indentation.

**Review by konan-abhi — APPROVED** [review]
It would have been better to handle indentation fix in separate PR, but since we have two jira mentioned in commit so no objection.

**Review by jistr — APPROVED** [review]

**Pull request merged**
