### PR TITLE
Change docs layout

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by jistr** [comment]
Looks unchanged? https://logserver.rdoproject.org/52/352/2c4f1b1634f26433630f810bcadede361e9f147a/github-check/adoption-docs-preview/52d9979/docs_build/docs_build/adoption-user/index-upstream.html

**Comment by fao89** [comment]
Actually, it is minor things such as icons and callouts, I have an example here: https://github.com/openstack-k8s-operators/dataplane-operator/pull/762

**Comment by fao89** [comment]
current:
image
image


PR:
image
image

**Comment by jistr** [comment]
Ah cool, that looks good then. @klgill is this ok from downstream perspective? I think we don't use the upstream `main.adoc` file downstream?

**Comment by klgill** [comment]
> Ah cool, that looks good then. @klgill is this ok from downstream perspective? I think we don't use the upstream `main.adoc` file downstream?

You're right. We don't use the main.adoc file downstream. These notes are going to look a bit different when rendered downstream. For example, the asciidoc formatting is [IMPORTANT] and [WARNING]. I think this is fine for upstream, and then I'll change the formatting downstream eventually.

**Review by klgill — APPROVED** [review]

**Pull request merged**
