### PR TITLE
[DP3] Remove mentions of OS Diff for DP3

### PR DESCRIPTION
**Pull request by jistr**
OS Diff will only come after DP3.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by klgill** [comment]
Just one question: Do you want to comment out the text related to os-diff rather than delete it, in case we need it after DP3?

**Comment by jistr** [comment]
The content stays untouched on the main branch, this PR only affects the DP3 branch. The further branches for beta/GA should be forked again from main, not from dev-preview3 branch.

For example, after we merge this, all the OS Diff content would still be present in https://openstack-k8s-operators.github.io/data-plane-adoption/user/ .

**Comment by jistr** [comment]
We just need to make sure when we want to take the DP3 docs downstream, we have to use the dev-preview3 branch which was created for this purpose, rather than the main branch.

**Comment by klgill** [comment]
> The content stays untouched on the main branch, this PR only affects the DP3 branch. The further branches for beta/GA should be forked again from main, not from dev-preview3 branch.
> 
> For example, after we merge this, all the OS Diff content would still be present in https://openstack-k8s-operators.github.io/data-plane-adoption/user/ .

Yes, that makes sense.

**Pull request merged**
