### PR TITLE
Add second compute node info and nova_adoption in rhev dataplane role.

### PR DESCRIPTION
**Pull request by archana203**
- Add nova_adoption role in test-minimal-rhev
- Add second compute node details

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
could you please try `make test-minimal` on RHEV?
If it works, we can try add an extranode var here: https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/dataplane_adoption/vars/rhev.yaml

**Comment by archana203** [comment]
I tried make test-minimal on RHEV and figure out some changes: 
1. additional localdomain with compute hostnames while populating the computes list.
**computes=([\"compute-0.redhat.local.localdomain\"]=\"192.168.23.10\")", "+ for name in \"${!computes[@]}\"", "++ oc exec -t openstackclient -- openstack hypervisor show compute-0.redhat.local.localdomain -f value -c id", "No Hypervisor found for compute-0.redhat.local.localdomain**
2. edpm_user needs to be root 
echo f2467a99-4593-44ba-a60f-608be8fee2fa > /var/lib/nova/compute_id'", "bash: line 1: /var/lib/nova/compute_id: Permission denied"

**Comment by fao89** [comment]
We can change the user here:
https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/dataplane_adoption/vars/rhev.yaml#L54

about the localdomain, maybe we have to change this: https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/dataplane_adoption/vars/rhev.yaml#L39

**Comment by fao89** [comment]
@gibizer @bogdando do you know what needs to be adjusted for populating compute_id file in RHEV?

**Comment by fao89** [comment]
I'm working on https://github.com/openstack-k8s-operators/data-plane-adoption/pull/219

**Comment by archana203** [comment]
ssh login for root user is not enabled in our RHEV source osp nodes.
changing root user here will not help: https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/dataplane_adoption/vars/rhev.yaml#L54

**Comment by fao89** [comment]
@archana203 I've added `sudo` here:https://github.com/openstack-k8s-operators/data-plane-adoption/pull/219/files#r1446079023

**Comment by gibizer** [comment]
> @gibizer @bogdando do you know what needs to be adjusted for populating compute_id file in RHEV?

In general as soon as https://github.com/openstack-k8s-operators/edpm-ansible/pull/498 lands all adoption to OSP 18 needs to pre-populate the compute_id file before running OSP 18 deployment on the compute node. Otherwise nova-compute on OSP18 will fail to start up.

**Comment by fao89** [comment]
addressed here https://github.com/openstack-k8s-operators/data-plane-adoption/pull/219/files#r1476494975

**Pull request closed without merging**
