### PR TITLE
Retry the reset of crc storage 3 times

### PR DESCRIPTION
**Pull request by jistr**

### CODE REVIEW

**Review by davidjpeacock — APPROVED** [review]
LGTM

**Review by fao89 — APPROVED** [review]

**Comment by jistr** [comment]
It gets further than in the other PRs it seems but still containers stuck in Pending:
```
NAME                                                              READY   STATUS      RESTARTS        AGE
21c00fa25cd18552df0f30140d513a269a60ecb7e348dc2f85fce73c8ec6cwm   0/1     Completed   0               100m
cinder-operator-controller-manager-86d49cd449-xmxn7               2/2     Running     5 (9m6s ago)    99m
controller-manager-567b48c6-ffk9z                                 1/1     Running     3 (9m7s ago)    99m
dataplane-operator-controller-manager-864d49d897-t6st4            2/2     Running     3 (11m ago)     99m
fdb3dbaba7f5dabfb12cc7a0d4b0e31ecf91f26868fe8d08e55c7f6f27hrfwq   0/1     Completed   0               100m
glance-operator-controller-manager-5b96b48c64-fdn54               2/2     Running     4 (11m ago)     99m
horizon-operator-controller-manager-5456659865-6mjfn              2/2     Running     3 (9m7s ago)    99m
infra-operator-controller-manager-85b8c756b8-2gsxj                2/2     Running     3 (11m ago)     99m
ironic-operator-controller-manager-584686b66c-5wzfh               2/2     Running     3 (11m ago)     99m
keystone-operator-controller-manager-6dd7fff7-fl667               2/2     Running     3 (9m4s ago)    99m
manila-operator-controller-manager-857949f967-zn8gf               2/2     Running     4 (9m7s ago)    99m
mariadb-operator-controller-manager-6888db6b96-49nj7              2/2     Running     4 (9m22s ago)   99m
neutron-operator-controller-manager-5b677d95d5-ksl47              2/2     Running     3 (9m4s ago)    99m
nova-operator-controller-manager-6cccc674cc-qcdjk                 2/2     Running     5 (9m1s ago)    99m
openstack-ansibleee-operator-controller-manager-6ff59cb56dprhg7   2/2     Running     4 (9m4s ago)    99m
openstack-baremetal-operator-controller-manager-5558c9f845ctqjp   2/2     Running     4 (11m ago)     99m
openstack-db-init-5grz2                                           0/1     Pending     0               2m27s
openstack-operator-controller-manager-697868dd88-6s8rk            2/2     Running     4 (9m4s ago)    99m
openstack-operator-index-f7txr                                    1/1     Running     0               100m
ovn-operator-controller-manager-858d59cc9f-4p8lh                  2/2     Running     4 (9m22s ago)   99m
ovs-operator-controller-manager-6868d89fbc-rhnfd                  2/2     Running     3 (11m ago)     99m
placement-operator-controller-manager-544795597d-m6sbf            2/2     Running     3 (11m ago)     99m
rabbitmq-cell1-server-0                                           0/1     Pending     0               2m26s
rabbitmq-server-0                                                 0/1     Pending     0               2m29s
```

And i don't see any helpful info in MariaDB / Rabbit operator output.

@marios I wonder if it could be some disk/RAM pressure causing that the pods aren't being scheduled... That would also explain the failures in `make crc_storage_cleanup` -- locally i've seen those when my CRC VM was no longer big enough to accomodate the growing set of Operators...

**Comment by jistr** [comment]
Also the "clean up any remains of podified deployment" task does seem to be cleaning remains of previous podified deployment. So the job is probably deploying PCP, then removing it, then doing Adoption? If so, we could perhaps make it lighter by not deploying PCP at the beginning.

**Comment by jistr** [comment]
Trying a depends-on with https://review.rdoproject.org/r/c/rdo-jobs/+/48480 to get a XXL instance, in case the issue is resource pressure.

**Comment by fao89** [comment]
we might need something like this:
https://github.com/openstack-k8s-operators/install_yamls/pull/255/files

to reduce resource consumption

**Comment by jistr** [comment]
MariaDB failed to start because:

```
NAME                                                              READY   STATUS                  RESTARTS   AGE
1b249e42537888d1d8546c5e4667ffd7287af36cf989e0ab6cf37f5dbd9lj42   0/1     Completed               0          63m
ada98f566246c036bdb1b8029d9bbf22cb03f3bdab9c9fc2540335f1cfnqd7v   0/1     Completed               0          63m
cinder-operator-controller-manager-68cd5b6768-jj4pg               2/2     Running                 0          62m
controller-manager-7fc8ffd989-v4jzk                               1/1     Running                 0          62m
dataplane-operator-controller-manager-5966f58c89-q6plz            2/2     Running                 0          62m
glance-operator-controller-manager-77d68bd684-n8ncg               2/2     Running                 0          62m
horizon-operator-controller-manager-64d6c84dc6-nrvsw              2/2     Running                 0          62m
infra-operator-controller-manager-5dc8cdc5f4-vh5qr                2/2     Running                 0          62m
ironic-operator-controller-manager-7465d6cddb-v9f87               1/2     ImagePullBackOff        0          62m
keystone-operator-controller-manager-886cc466d-nskdk              1/2     ImagePullBackOff        0          62m
manila-operator-controller-manager-6f94f7bf95-d2dmr               2/2     Running                 0          62m
mariadb-operator-controller-manager-5859875f4-zktxc               1/2     ImagePullBackOff        0          62m
neutron-operator-controller-manager-ddcfbbb8-f747m                2/2     Running                 0          62m
nova-operator-controller-manager-7776c7bb86-9997r                 2/2     Running                 0          62m
openstack-ansibleee-operator-controller-manager-787f8cf665b44wk   2/2     Running                 0          62m
openstack-baremetal-operator-controller-manager-66c8c78cd-6nxwc   2/2     Running                 0          62m
openstack-operator-controller-manager-6757cc7bb8-slv2b            2/2     Running                 0          62m
openstack-operator-index-chp2k                                    1/1     Running                 0          63m
ovn-operator-controller-manager-97d74d8dc-5rpmf                   2/2     Running                 0          62m
ovs-operator-controller-manager-5b789f9c58-qp254                  2/2     Running                 0          62m
placement-operator-controller-manager-cb5f7d495-7qhvb             2/2     Running                 0          62m
rabbitmq-cell1-server-0                                           0/1     Pending                 0          2m20s
rabbitmq-server-0                                                 0/1     Init:ImagePullBackOff   0          2m21s
```

**Comment by abays** [comment]
> MariaDB failed to start because:
> 
> ```
> NAME                                                              READY   STATUS                  RESTARTS   AGE
> 1b249e42537888d1d8546c5e4667ffd7287af36cf989e0ab6cf37f5dbd9lj42   0/1     Completed               0          63m
> ada98f566246c036bdb1b8029d9bbf22cb03f3bdab9c9fc2540335f1cfnqd7v   0/1     Completed               0          63m
> cinder-operator-controller-manager-68cd5b6768-jj4pg               2/2     Running                 0          62m
> controller-manager-7fc8ffd989-v4jzk                               1/1     Running                 0          62m
> dataplane-operator-controller-manager-5966f58c89-q6plz            2/2     Running                 0          62m
> glance-operator-controller-manager-77d68bd684-n8ncg               2/2     Running                 0          62m
> horizon-operator-controller-manager-64d6c84dc6-nrvsw              2/2     Running                 0          62m
> infra-operator-controller-manager-5dc8cdc5f4-vh5qr                2/2     Running                 0          62m
> ironic-operator-controller-manager-7465d6cddb-v9f87               1/2     ImagePullBackOff        0          62m
> keystone-operator-controller-manager-886cc466d-nskdk              1/2     ImagePullBackOff        0          62m
> manila-operator-controller-manager-6f94f7bf95-d2dmr               2/2     Running                 0          62m
> mariadb-operator-controller-manager-5859875f4-zktxc               1/2     ImagePullBackOff        0          62m
> neutron-operator-controller-manager-ddcfbbb8-f747m                2/2     Running                 0          62m
> nova-operator-controller-manager-7776c7bb86-9997r                 2/2     Running                 0          62m
> openstack-ansibleee-operator-controller-manager-787f8cf665b44wk   2/2     Running                 0          62m
> openstack-baremetal-operator-controller-manager-66c8c78cd-6nxwc   2/2     Running                 0          62m
> openstack-operator-controller-manager-6757cc7bb8-slv2b            2/2     Running                 0          62m
> openstack-operator-index-chp2k                                    1/1     Running                 0          63m
> ovn-operator-controller-manager-97d74d8dc-5rpmf                   2/2     Running                 0          62m
> ovs-operator-controller-manager-5b789f9c58-qp254                  2/2     Running                 0          62m
> placement-operator-controller-manager-cb5f7d495-7qhvb             2/2     Running                 0          62m
> rabbitmq-cell1-server-0                                           0/1     Pending                 0          2m20s
> rabbitmq-server-0                                                 0/1     Init:ImagePullBackOff   0          2m21s
> ```

I recently rebuilt and re-pushed the OpenStack operator images to attempt to fix this problem.  It seemed to work when I tested it in my environment.  Perhaps we can try here again.

**Comment by fao89** [comment]
recheck

**Comment by jistr** [comment]
@abays Thanks, we now also rebased and merged https://review.rdoproject.org/r/c/rdo-jobs/+/48539 - XXL instance rather than XL for the CRC node.

(I had that in depends-on in this PR's patch previously, but we just discussed in a call today that pulling Zuul patches in as deps via commit messages in Github PRs isn't supported, so that dependency wasn't doing anything, we were still using the XL node in previous runs, which might have been the cause of some of the weird failures.)

**Comment by jistr** [comment]
Hooray! Green CI, merging.

**Pull request merged**
