### PR TITLE
Exit early if DataPlaneDeployment is failing

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by jistr — APPROVED** [review]
LGTM, thanks!

**Comment by gibizer** [comment]
recheck retry limit

**Comment by gibizer** [comment]
rechec
```
Cannot find device "virbr0"
gmake: *** [Makefile:600: crc_bmo_setup] Error 1
```

**Comment by gibizer** [comment]
recheck network issue

**Comment by cescgina** [comment]
@gibizer the issue you're seeing with `missing virbr0` is a legit issue that I'm working on, please hold the rechecks for a while, sorry I missed the notifications before

**Comment by cescgina** [comment]
recheck

**Pull request merged**
