### PR TITLE
Updating EDPM variables

### PR DESCRIPTION
**Pull request by fao89**
Cacthing up with dataplane-operator updates + new dev environment

### CODE REVIEW

**Comment by fao89** [comment]
I got past the os-net-config error, but now I'm facing an error with `nova-deploy-libvirt`
```
oc get pod -l app=openstackansibleee -w
NAME                                                        READY   STATUS    RESTARTS   AGE
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Pending   0          0s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Pending   0          0s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     ContainerCreating   0          0s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     ContainerCreating   0          11s
dataplane-deployment-configure-network-edpmadoption-j6r4l   1/1     Running             0          37s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m23s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m35s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m36s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Pending             0          0s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Pending             0          0s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     ContainerCreating   0          0s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     ContainerCreating   0          11s
dataplane-deployment-validate-network-edpmadoption-6g7n9    1/1     Running             0          13s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          22s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          33s
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          34s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Pending             0          0s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Pending             0          0s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     ContainerCreating   0          0s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     ContainerCreating   0          11s
dataplane-deployment-install-os-edpmadoption-7vz4d          1/1     Running             0          14s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m28s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m39s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m40s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Pending             0          0s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Pending             0          0s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     ContainerCreating   0          0s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     ContainerCreating   0          11s
dataplane-deployment-configure-os-edpmadoption-crmgn        1/1     Running             0          14s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m35s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m46s
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m47s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Pending             0          0s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Pending             0          0s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     ContainerCreating   0          0s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     ContainerCreating   0          11s
dataplane-deployment-run-os-edpmadoption-4nxgx              1/1     Running             0          13s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m17s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m28s
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m29s
nova-standalone-deploy-libvirt-bhbs8                        0/1     Pending             0          0s
nova-standalone-deploy-libvirt-bhbs8                        0/1     Pending             0          0s
nova-standalone-deploy-nova-fxlrf                           0/1     Pending             0          0s
nova-standalone-deploy-nova-fxlrf                           0/1     Pending             0          0s
nova-standalone-deploy-libvirt-bhbs8                        0/1     ContainerCreating   0          0s
nova-standalone-deploy-nova-fxlrf                           0/1     ContainerCreating   0          0s
nova-standalone-deploy-libvirt-bhbs8                        0/1     ContainerCreating   0          2s
nova-standalone-deploy-nova-fxlrf                           0/1     ContainerCreating   0          2s
nova-standalone-deploy-libvirt-bhbs8                        1/1     Running             0          4s
nova-standalone-deploy-nova-fxlrf                           1/1     Running             0          5s
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Terminating         0          13m
dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Terminating         0          13m
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Terminating         0          10m
dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Terminating         0          10m
nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          66s
nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          68s
nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          69s
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Terminating         0          12m
dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Terminating         0          12m
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Terminating         0          12m
dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Terminating         0          12m
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Terminating         0          13m
dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Terminating         0          13m
nova-standalone-deploy-nova-fxlrf                           0/1     Terminating         0          11m
nova-standalone-deploy-nova-fxlrf                           0/1     Terminating         0          11m
nova-standalone-deploy-libvirt-bhbs8                        0/1     Error               0          11m
nova-standalone-deploy-libvirt-bhbs8                        0/1     Error               0          11m
```
```
oc logs -l app=openstackansibleee -f
...

TASK [update ceph libvirt secret] **********************************************
fatal: [standalone]: FAILED! => {"changed": true, "cmd": "CLUSTERS=( $(ls /etc/ceph/*.conf | xargs -I {} basename  -s .conf {} ) )\ndeclare -A CLUSTER_USER_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_USER_MAP[${cluster}]=$(ls /etc/ceph/${cluster}.client.*.keyring | grep -v admin | awk -F . '{print $3}'); done\ndeclare -A CLUSTER_FSID_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_FSID_MAP[${cluster}]=$(awk -F '=' '/fsid/ {print $2}' /etc/ceph/${cluster}.conf| xargs); done\nfor cluster in ${CLUSTERS[@]}; do\ncat <<EOF | tee secret.xml>/dev/null\n<secret ephemeral='no' private='no'>\n<uuid>${CLUSTER_FSID_MAP[${cluster}]}</uuid>\n<usage type='ceph'>\n    <name>${cluster}.client.${CLUSTER_USER_MAP[$cluster]} secret</name>\n</usage>\n</secret>\nEOF\npodman cp secret.xml libvirt_virtqemud:/tmp/secret.xml\nrm -f secret.xml\npodman exec libvirt_virtqemud bash -c \"virsh secret-undefine ${CLUSTER_FSID_MAP[${cluster}]}\"\npodman exec libvirt_virtqemud bash -c \"virsh secret-define --file /tmp/secret.xml; rm -f /tmp/secret.xml\"\nkeyring=$(awk '$1 == \"key\" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)\npodman exec libvirt_virtqemud bash -c \"virsh secret-set-value ${CLUSTER_FSID_MAP[${cluster}]} --base64 ${keyring}\"\ndone\n", "delta": "0:00:01.058998", "end": "2023-06-22 20:46:52.210430", "msg": "non-zero return code", "rc": 1, "start": "2023-06-22 20:46:51.151432", "stderr": "awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory\nerror: expected syntax: --base64 <string>", "stderr_lines": ["awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory", "error: expected syntax: --base64 <string>"], "stdout": "Secret 9992062f-2fe0-5aa8-8e13-039523711a28 deleted\n\nSecret 9992062f-2fe0-5aa8-8e13-039523711a28 created", "stdout_lines": ["Secret 9992062f-2fe0-5aa8-8e13-039523711a28 deleted", "", "Secret 9992062f-2fe0-5aa8-8e13-039523711a28 created"]}
```

**Comment by fultonj** [comment]
> I got past the os-net-config error, but now I'm facing an error with `nova-deploy-libvirt`
> 
> ```
> oc get pod -l app=openstackansibleee -w
> NAME                                                        READY   STATUS    RESTARTS   AGE
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Pending   0          0s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Pending   0          0s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     ContainerCreating   0          0s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     ContainerCreating   0          11s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   1/1     Running             0          37s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m23s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m35s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Completed           0          3m36s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Pending             0          0s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Pending             0          0s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     ContainerCreating   0          0s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     ContainerCreating   0          11s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    1/1     Running             0          13s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          22s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          33s
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Completed           0          34s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Pending             0          0s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Pending             0          0s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     ContainerCreating   0          0s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     ContainerCreating   0          11s
> dataplane-deployment-install-os-edpmadoption-7vz4d          1/1     Running             0          14s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m28s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m39s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Completed           0          2m40s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Pending             0          0s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Pending             0          0s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     ContainerCreating   0          0s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     ContainerCreating   0          11s
> dataplane-deployment-configure-os-edpmadoption-crmgn        1/1     Running             0          14s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m35s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m46s
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Completed           0          2m47s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Pending             0          0s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Pending             0          0s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     ContainerCreating   0          0s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     ContainerCreating   0          11s
> dataplane-deployment-run-os-edpmadoption-4nxgx              1/1     Running             0          13s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m17s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m28s
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Completed           0          3m29s
> nova-standalone-deploy-libvirt-bhbs8                        0/1     Pending             0          0s
> nova-standalone-deploy-libvirt-bhbs8                        0/1     Pending             0          0s
> nova-standalone-deploy-nova-fxlrf                           0/1     Pending             0          0s
> nova-standalone-deploy-nova-fxlrf                           0/1     Pending             0          0s
> nova-standalone-deploy-libvirt-bhbs8                        0/1     ContainerCreating   0          0s
> nova-standalone-deploy-nova-fxlrf                           0/1     ContainerCreating   0          0s
> nova-standalone-deploy-libvirt-bhbs8                        0/1     ContainerCreating   0          2s
> nova-standalone-deploy-nova-fxlrf                           0/1     ContainerCreating   0          2s
> nova-standalone-deploy-libvirt-bhbs8                        1/1     Running             0          4s
> nova-standalone-deploy-nova-fxlrf                           1/1     Running             0          5s
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Terminating         0          13m
> dataplane-deployment-configure-network-edpmadoption-j6r4l   0/1     Terminating         0          13m
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Terminating         0          10m
> dataplane-deployment-validate-network-edpmadoption-6g7n9    0/1     Terminating         0          10m
> nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          66s
> nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          68s
> nova-standalone-deploy-nova-fxlrf                           0/1     Completed           0          69s
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Terminating         0          12m
> dataplane-deployment-install-os-edpmadoption-7vz4d          0/1     Terminating         0          12m
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Terminating         0          12m
> dataplane-deployment-configure-os-edpmadoption-crmgn        0/1     Terminating         0          12m
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Terminating         0          13m
> dataplane-deployment-run-os-edpmadoption-4nxgx              0/1     Terminating         0          13m
> nova-standalone-deploy-nova-fxlrf                           0/1     Terminating         0          11m
> nova-standalone-deploy-nova-fxlrf                           0/1     Terminating         0          11m
> nova-standalone-deploy-libvirt-bhbs8                        0/1     Error               0          11m
> nova-standalone-deploy-libvirt-bhbs8                        0/1     Error               0          11m
> ```
> 
> ```
> oc logs -l app=openstackansibleee -f
> ...
> 
> TASK [update ceph libvirt secret] **********************************************
> fatal: [standalone]: FAILED! => {"changed": true, "cmd": "CLUSTERS=( $(ls /etc/ceph/*.conf | xargs -I {} basename  -s .conf {} ) )\ndeclare -A CLUSTER_USER_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_USER_MAP[${cluster}]=$(ls /etc/ceph/${cluster}.client.*.keyring | grep -v admin | awk -F . '{print $3}'); done\ndeclare -A CLUSTER_FSID_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_FSID_MAP[${cluster}]=$(awk -F '=' '/fsid/ {print $2}' /etc/ceph/${cluster}.conf| xargs); done\nfor cluster in ${CLUSTERS[@]}; do\ncat <<EOF | tee secret.xml>/dev/null\n<secret ephemeral='no' private='no'>\n<uuid>${CLUSTER_FSID_MAP[${cluster}]}</uuid>\n<usage type='ceph'>\n    <name>${cluster}.client.${CLUSTER_USER_MAP[$cluster]} secret</name>\n</usage>\n</secret>\nEOF\npodman cp secret.xml libvirt_virtqemud:/tmp/secret.xml\nrm -f secret.xml\npodman exec libvirt_virtqemud bash -c \"virsh secret-undefine ${CLUSTER_FSID_MAP[${cluster}]}\"\npodman exec libvirt_virtqemud bash -c \"virsh secret-define --file /tmp/secret.xml; rm -f /tmp/secret.xml\"\nkeyring=$(awk '$1 == \"key\" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)\npodman exec libvirt_virtqemud bash -c \"virsh secret-set-value ${CLUSTER_FSID_MAP[${cluster}]} --base64 ${keyring}\"\ndone\n", "delta": "0:00:01.058998", "end": "2023-06-22 20:46:52.210430", "msg": "non-zero return code", "rc": 1, "start": "2023-06-22 20:46:51.151432", "stderr": "awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory\nerror: expected syntax: --base64 <string>", "stderr_lines": ["awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory", "error: expected syntax: --base64 <string>"], "stdout": "Secret 9992062f-2fe0-5aa8-8e13-039523711a28 deleted\n\nSecret 9992062f-2fe0-5aa8-8e13-039523711a28 created", "stdout_lines": ["Secret 9992062f-2fe0-5aa8-8e13-039523711a28 deleted", "", "Secret 9992062f-2fe0-5aa8-8e13-039523711a28 created"]}
> ```

Two questions:

1. Is /etc/ceph/ populated on your edpm node? 
2. Did you use an extraMounts as described here? https://github.com/openstack-k8s-operators/docs/blob/main/ceph.md#access-the-ceph-secret-via-extramounts

I don't see any evidence that this role ran from your `oc get pod -l app=openstackansibleee` output

  https://github.com/openstack-k8s-operators/edpm-ansible/tree/main/roles/edpm_ceph_client_files

So my conjecture is that the file the nova ansible is looking for is not there. If extraMounts is used, then the file should be populated.

**Comment by fao89** [comment]
```
[root@standalone ~]# ls /etc/ceph/
ceph.client.admin.keyring      ceph.client.radosgw.keyring
ceph.client.openstack.keyring  ceph.conf
```
Yes, I followed: https://openstack-k8s-operators.github.io/data-plane-adoption/contributing/development_environment/
and got a standalone node with ceph, but I forgot extramounts in both ctlplane and dataplane operators

**Review by fultonj — APPROVED** [review]
/lgtm

+2

**Comment by fao89** [comment]
I did get the same error with Ceph,
so I got the script from: https://github.com/openstack-k8s-operators/nova-operator/blob/main/playbooks/deploy-libvirt.yaml#L105-L128
and ran manually:
```
[root@standalone ~]# CLUSTERS=( $(ls /etc/ceph/*.conf | xargs -I {} basename  -s .conf {} ) )                                                                                                 
declare -A CLUSTER_USER_MAP=()                                                                                                                                                                
for cluster in ${CLUSTERS[@]}; do CLUSTER_USER_MAP[${cluster}]=$(ls /etc/ceph/${cluster}.client.*.keyring | grep -v admin | awk -F . '{print $3}'); done                                      
declare -A CLUSTER_FSID_MAP=()                                                                                                                                                                
for cluster in ${CLUSTERS[@]}; do CLUSTER_FSID_MAP[${cluster}]=$(awk -F '=' '/fsid/ {print $2}' /etc/ceph/${cluster}.conf| xargs); done                                                       
for cluster in ${CLUSTERS[@]}; do                                                                                                                                                             
cat <<EOF | tee secret.xml>/dev/null                                                                                                                                                          
<secret ephemeral='no' private='no'>                                                                                                                                                          
<uuid>${CLUSTER_FSID_MAP[${cluster}]}</uuid>                                                                                                                                                  
<usage type='ceph'>                                                                                                                                                                           
    <name>${cluster}.client.${CLUSTER_USER_MAP[$cluster]} secret</name>                                                                                                                       
</usage>                                                                                                                                                                                      
</secret>                                                                                                                                                                                     
EOF                                                                                                                                                                                           
podman cp secret.xml libvirt_virtqemud:/tmp/secret.xml                                                                                                                                        
rm -f secret.xml                                                                                                                                                                              
podman exec libvirt_virtqemud bash -c "virsh secret-undefine ${CLUSTER_FSID_MAP[${cluster}]}"                                                                                                 
podman exec libvirt_virtqemud bash -c "virsh secret-define --file /tmp/secret.xml; rm -f /tmp/secret.xml"                                                                                     
keyring=$(awk '$1 == "key" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$clusterdonese64 ${keyring}"virtqemud bash -c "virsh secret-set-value ${CLUSTER_FSID_MAP[${cluster}]}   
Secret 9008d71a-4aca-5c7b-a683-6106069046d6 deleted                                                                                                                                           
                                                                                                                                                                                              
Secret 9008d71a-4aca-5c7b-a683-6106069046d6 created                                                                                                                                           
                                                                                                                                                                                              
awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory                                                                                         
error: expected syntax: --base64 <string>                                                                      
```
`/etc/ceph/ceph.client.openstack` wasn't there indeed:
```
[root@standalone ~]# ls /etc/ceph                                                                                                                                                             
ceph.client.admin.keyring      ceph.client.radosgw.keyring                                                                                                                                    
ceph.client.openstack.keyring  ceph.conf        
```
then I created the file:
```
[root@standalone ~]# cp /etc/ceph/ceph.client.openstack.keyring /etc/ceph/ceph.client.openstack 
[root@standalone ~]# ls /etc/ceph                                                              
ceph.client.admin.keyring  ceph.client.openstack.keyring  ceph.conf                            
ceph.client.openstack      ceph.client.radosgw.keyring                           
```
and then the deploy succeeded:
```TASK [update ceph libvirt secret] **********************************************
changed: [standalone] => {"changed": true, "cmd": "CLUSTERS=( $(ls /etc/ceph/*.conf | xargs -I {} basename  -s .conf {} ) )\ndeclare -A CLUSTER_USER_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_USER_MAP[${cluster}]=$(ls /etc/ceph/${cluster}.client.*.keyring | grep -v admin | awk -F . '{print $3}'); done\ndeclare -A CLUSTER_FSID_MAP=()\nfor cluster in ${CLUSTERS[@]}; do CLUSTER_FSID_MAP[${cluster}]=$(awk -F '=' '/fsid/ {print $2}' /etc/ceph/${cluster}.conf| xargs); done\nfor cluster in ${CLUSTERS[@]}; do\ncat <<EOF | tee secret.xml>/dev/null\n<secret ephemeral='no' private='no'>\n<uuid>${CLUSTER_FSID_MAP[${cluster}]}</uuid>\n<usage type='ceph'>\n    <name>${cluster}.client.${CLUSTER_USER_MAP[$cluster]} secret</name>\n</usage>\n</secret>\nEOF\npodman cp secret.xml libvirt_virtqemud:/tmp/secret.xml\nrm -f secret.xml\npodman exec libvirt_virtqemud bash -c \"virsh secret-undefine ${CLUSTER_FSID_MAP[${cluster}]}\"\npodman exec libvirt_virtqemud bash -c \"virsh secret-define --file /tmp/secret.xml; rm -f /tmp/secret.xml\"\nkeyring=$(awk '$1 == \"key\" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)\npodman exec libvirt_virtqemud bash -c \"virsh secret-set-value ${CLUSTER_FSID_MAP[${cluster}]} --base64 ${keyring}\"\ndone\n", "delta": "0:00:01.183442", "end": "2023-06-26 19:13:17.236997", "msg": "", "rc": 0, "start": "2023-06-26 19:13:16.053555", "stderr": "awk: cmd. line:1: fatal: cannot open file `radosgw.keyring' for reading: No such file or directory\nerror: Passing secret value as command-line argument is insecure!", "stderr_lines": ["awk: cmd. line:1: fatal: cannot open file `radosgw.keyring' for reading: No such file or directory", "error: Passing secret value as command-line argument is insecure!"], "stdout": "Secret 9008d71a-4aca-5c7b-a683-6106069046d6 deleted\n\nSecret 9008d71a-4aca-5c7b-a683-6106069046d6 created\n\nSecret value set", "stdout_lines": ["Secret 9008d71a-4aca-5c7b-a683-6106069046d6 deleted", "", "Secret 9008d71a-4aca-5c7b-a683-6106069046d6 created", "", "Secret value set"]}
...
PLAY RECAP *********************************************************************
standalone                 : ok=18   changed=8    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 
```

**Comment by fultonj** [comment]
> https://github.com/openstack-k8s-operators/nova-operator/blob/main/playbooks/deploy-libvirt.yaml#L105-L128

This line of awk:

  https://github.com/openstack-k8s-operators/nova-operator/blob/main/playbooks/deploy-libvirt.yaml#L126

```
keyring=$(awk '$1 == "key" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)
```
Is not finding the file unless you rename it to remove the ".keyring" suffix.

It's a bug if it can't handle `/etc/ceph/ceph.client.openstack.keyring` since that's what the file is supposed to be called. 

I suspect if you rename the file correctly (putting .keyring back) and then edit the line of awk like this, that it will work:

```
keyring=$(awk '$1 == "key" {print $3}' /etc/ceph/${cluster}.client.openstack.keyring)
```

That might show that the awk embedded in ansible shell is having an interpolation issue. I haven't hit the same issue myself however.

**Comment by fao89** [comment]
FYI @gibizer @SeanMooney ^

**Comment by fao89** [comment]
I've filed this: https://github.com/openstack-k8s-operators/nova-operator/issues/424

**Comment by fultonj** [comment]
> I've filed this: [openstack-k8s-operators/nova-operator#424](https://github.com/openstack-k8s-operators/nova-operator/issues/424)

I see a workaround. When following this step:

https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/docs/contributing/development_environment.md#openstack

and running this command 

```
sudo openstack tripleo deploy \
  ...
  -e /usr/share/openstack-tripleo-heat-templates/environments/cephadm/cephadm.yaml \
```

replace `environments/cephadm/cephadm.yaml` with `environments/cephadm/cephadm-rbd-only.yaml`.

That will prevent the radosgw key from being created (the problem in 424 is that it cannot handle when that key is there).

**Comment by SeanMooney** [comment]
as noted in https://github.com/openstack-k8s-operators/nova-operator/issues/315 we do not support multiple user pre cluster currently

that was a know limitation in the q1 demo and that has not been resolved yet.

at this point it will not be resolved until q3

the other think to not is its important to test adoption both with ceph and without.

the default for both tripleo and the next gen installer is to use local storage so we should not only test with ceph/rbd for nova.

**Pull request merged**
