### PR TITLE
Enable dataplane adotion test

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by cescgina — COMMENTED** [review]
looks good to me, will this change require creating a new vm for compute in CI?

**Comment by fao89** [comment]
> looks good to me, will this change require creating a new vm for compute in CI?

it reuses the standalone node

**Comment by jistr** [comment]
Great! One thing we should follow up on in another PR perhaps -- right now the last thing that the test suite does is creation of the OpenStackDataPlane CR [1] and beyond OpenShift not complaining that the CR has a formatting issue, we don't know what happens next -- e.g. whether Ansible can connect to the Standalone node or not. We should add some check that the DataPlane CR gets reconciled.

[1] https://github.com/openstack-k8s-operators/data-plane-adoption/blob/3232403e6baef84ec267593c98745cc01dfd9093/tests/roles/dataplane_adoption/tasks/main.yaml#L57

**Review by jistr — APPROVED** [review]

**Comment by jistr** [comment]
We could also remove the compute role from the node configuration if that's possible now, so that EDPM would run essentially an "empty playbook" on the node. In my mind that still goes a long way in terms of CI-ing that EDPM is integrated correctly and we can control the Standalone node with it. And making it an actual working compute node can come later.

Or as you say we can wait for the Nova adoption. We could perhaps decide based on the ETA for the Nova implementation.

**Comment by fao89** [comment]
if we enable it, we will the ansible running on the standalone node, but it will fail when trying to deploy libvirt and nova

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by cescgina** [comment]
@fao89 the error in the last failure looks like what I'm trying to solve with https://github.com/openstack-k8s-operators/data-plane-adoption/pull/68, so we probably should get that in before, although I can't make any promises because we've been seeing a whole lot of crc errors as well

**Pull request merged**
