### PR TITLE
Transform contributor documentation into AsciiDoc + some docs rendering improvements

### PR DESCRIPTION
**Pull request by jistr**
This moves the contributor documentation from the mkdocs site to the new asciidoc site. The mkdocs site now links to the new site for the contributor part. Also i've done a bunch of improvements in the Makefiles related to local docs rendering.

What's worth mentioning is that the docs are transformed from a multi-page into a single-page rendering, following the STF docs example. https://infrawatch.github.io/documentation/

The single-page vs multi-page aspect is something that we'll need to discuss and solve before moving the main user-facing documentation.

### CODE REVIEW

**Comment by jistr** [comment]
I don't think this absolutely needs a green CI as the changes to the Makefile are pretty self-contained to docs only, but let's see if we can get it on the next attempt anyway...

**Comment by jistr** [comment]
recheck

**Comment by jistr** [comment]
Looks like the previous recheck didn't actually trigger a re-run, trying again.

**Comment by jistr** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
I think merge and iterate is the best way to go

**Comment by jistr** [comment]
Thanks, this will collide with #227 so we'll merge that one first and then i'll rebase this.

**Review by klgill — APPROVED** [review]

**Pull request merged**
