### PR TITLE
Cinder online migration

### PR DESCRIPTION
**Pull request by Akrog**
This PR adds to the cinder adoption process the missing DB online data migration step.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by jistr — CHANGES_REQUESTED** [review]
Would it be possible to add it to the test suite as well?

https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/tests/roles/cinder_adoption/tasks/main.yaml

**Comment by Akrog** [comment]
Good point!
I have added it to the latest update.

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by Akrog** [comment]
recheck

**Review by jistr — APPROVED** [review]
Thanks!

**Comment by Akrog** [comment]
recheck

**Comment by Akrog** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
