### PR TITLE
Add horizon adoption doc and tests

### PR DESCRIPTION
**Pull request by ashu-011**
This PR adds the adoption doc for horizon as well as the tests

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
please add `openstack/horizon_adoption.md` to this list:
https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/mkdocs.yml#L29

**Review by jistr — COMMENTED** [review]
Yes and also please add the horizon_adoption role to the lists in the test playbooks:

https://github.com/openstack-k8s-operators/data-plane-adoption/blob/33d1d68c3ee9d18c2bd2dca846dff058fb654c5e/tests/playbooks/test_minimal.yaml#L34

https://github.com/openstack-k8s-operators/data-plane-adoption/blob/33d1d68c3ee9d18c2bd2dca846dff058fb654c5e/tests/playbooks/test_with_ceph.yaml#L37

Other than that the PR is looking good, thanks!

**Comment by ashu-011** [comment]
Done , addressed review comments @jistr @fao89 thanks!

**Comment by jistr** [comment]
The CI went past horizon but broke on data plane, maybe we need this to merge first https://github.com/openstack-k8s-operators/data-plane-adoption/pull/137

**Review by jistr — APPROVED** [review]
LGTM we'll just need to get the CI green

**Comment by ashu-011** [comment]
recheck

**Review by fao89 — APPROVED** [review]
dataplane failure is unrelated

**Pull request merged**
