### PR TITLE
Remove variables that are automatically set by the dataplane-operator

### PR DESCRIPTION
**Pull request by fao89**
ref: https://github.com/openstack-k8s-operators/dataplane-operator/pull/325

### CODE REVIEW

**Comment by cescgina** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
https://github.com/openstack-k8s-operators/dataplane-operator/pull/344
https://github.com/openstack-k8s-operators/install_yamls/pull/472

**Pull request closed without merging**
