### PR TITLE
Disable horizon adoption test temporarily due to timeout OSPCIX-82

### PR DESCRIPTION
**Pull request by marios**
This blocks the current-podified promotion [1]

[1] https://issues.redhat.com/browse/OSPCIX-82

### CODE REVIEW

**Comment by fao89** [comment]
@ashu-011 do you know if anything changed in horizon-operator?

**Comment by ashu-011** [comment]
> @ashu-011 do you know if anything changed in horizon-operator?

Hi @fao89 , I am not aware of anything which could have caused this , let me check and get back on this . Maybe @bshephar could give us more info if anything has changed with the operator .

**Comment by marios** [comment]
as discussed in today's call @jistr I am now disabling the horizon test https://github.com/openstack-k8s-operators/data-plane-adoption/pull/168#event-10475005861

**Review by cescgina — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Review by jistr — APPROVED** [review]

**Review by arxcruz — APPROVED** [review]

**Comment by arxcruz** [comment]
recheck

**Comment by fao89** [comment]
we should merge as is, the dataplane is breaking because it needs https://github.com/openstack-k8s-operators/data-plane-adoption/pull/166

**Comment by arxcruz** [comment]
> we should merge as is, the dataplane is breaking because it needs #166

If you have the power, do it! :)

**Comment by marios** [comment]
This is failing on https://github.com/openstack-k8s-operators/data-plane-adoption/pull/166 
and that one needs this in order to merge

so I am merging this

**Comment by marios** [comment]
> > @ashu-011 do you know if anything changed in horizon-operator?
> 
> Hi @fao89 , I am not aware of anything which could have caused this , let me check and get back on this . Maybe @bshephar could give us more info if anything has changed with the operator .

I suspect the issue was caused by

https://github.com/openstack-k8s-operators/horizon-operator/pull/212 Update horizon to use service override #212

Seems relevant (routes for reaching the pod/service) and it merged Sep 20th which seems to line up with when this issue was seen

**Pull request merged**
