### PR TITLE
Make telemetry adoption conditional.

### PR DESCRIPTION
**Pull request by holser**
Since there are no real data migration telemetry role just creates a new telemetry installation. As it doesn't do any data migration it's not a mandatory for adoption. This patch makes a condition when telemetry can be turned on and off (default).

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by holser** [comment]
recheck

**Comment by holser** [comment]
recheck

**Comment by holser** [comment]
recheck

**Comment by holser** [comment]
recheck

**Comment by holser** [comment]
recheck

**Pull request merged**
